/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Forwards } from './forwards';

/**
* Account limits and usage
*/
export class AddressLimits {
    'forwards': Forwards;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "forwards",
            "baseName": "forwards",
            "type": "Forwards"
        }    ];

    static getAttributeTypeMap() {
        return AddressLimits.attributeTypeMap;
    }
}

