/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* List of attachments for this message
*/
export class Attachments {
    /**
    * Attachment ID
    */
    'id': string;
    /**
    * Filename of the attachment
    */
    'filename': string;
    /**
    * MIME type
    */
    'contentType': string;
    /**
    * Attachment disposition
    */
    'disposition': string;
    /**
    * Which transfer encoding was used (actual content when fetching attachments is not encoded)
    */
    'transferEncoding': string;
    /**
    * Was this attachment found from a multipart/related node. This usually means that this is an embedded image
    */
    'related': boolean;
    /**
    * Approximate size of the attachment in kilobytes
    */
    'sizeKb': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string"
        },
        {
            "name": "disposition",
            "baseName": "disposition",
            "type": "string"
        },
        {
            "name": "transferEncoding",
            "baseName": "transferEncoding",
            "type": "string"
        },
        {
            "name": "related",
            "baseName": "related",
            "type": "boolean"
        },
        {
            "name": "sizeKb",
            "baseName": "sizeKb",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Attachments.attributeTypeMap;
    }
}

