/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Parsed Content-Type header. Usually needed to identify encrypted messages and such
*/
export class ContentType {
    /**
    * MIME type of the message, eg. \"multipart/mixed\"
    */
    'value': string;
    /**
    * An object with Content-Type params as key-value pairs
    */
    'params': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return ContentType.attributeTypeMap;
    }
}

