/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CreateUserAddressRequest {
    /**
    * E-mail Address
    */
    'address': string;
    /**
    * Identity name
    */
    'name'?: string;
    /**
    * A list of tags associated with this address
    */
    'tags'?: Array<string>;
    /**
    * Indicates if this is the default address for the User
    */
    'main'?: boolean;
    /**
    * If true then address value can be in the form of `*@example.com`, `*suffix@example.com` and `username@*`, otherwise using * is not allowed. Static suffix can be up to 32 characters long.
    */
    'allowWildcard'?: boolean;
    /**
    * Optional metadata, must be an object or JSON formatted string
    */
    'metaData'?: object | string;
    /**
    * Optional metadata for internal use, must be an object or JSON formatted string of an object. Not available for user-role tokens
    */
    'internalData'?: object | string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "main",
            "baseName": "main",
            "type": "boolean"
        },
        {
            "name": "allowWildcard",
            "baseName": "allowWildcard",
            "type": "boolean"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "object | string"
        },
        {
            "name": "internalData",
            "baseName": "internalData",
            "type": "object | string"
        }    ];

    static getAttributeTypeMap() {
        return CreateUserAddressRequest.attributeTypeMap;
    }
}

