/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AddressOptionalName } from './addressOptionalName';

/**
* SMTP envelope. If not provided then resolved either from message headers or from referenced message
*/
export class EnvelopeUpload {
    'from'?: AddressOptionalName;
    /**
    * Recipients information
    */
    'to'?: Array<AddressOptionalName>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "AddressOptionalName"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Array<AddressOptionalName>"
        }    ];

    static getAttributeTypeMap() {
        return EnvelopeUpload.attributeTypeMap;
    }
}

