/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ForwardStoredMessageRequest {
    /**
    * Number of original forwarding target
    */
    'target'?: number;
    /**
    * An array of additional forward targets
    */
    'addresses'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "number"
        },
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ForwardStoredMessageRequest.attributeTypeMap;
    }
}

