/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Forwarded } from './forwarded';

export class ForwardStoredMessageResponse {
    /**
    * Indicates successful response
    */
    'success': boolean;
    /**
    * Message ID in outbound queue
    */
    'queueId': string;
    /**
    * Information about forwarding targets
    */
    'forwarded': Array<Forwarded>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "queueId",
            "baseName": "queueId",
            "type": "string"
        },
        {
            "name": "forwarded",
            "baseName": "forwarded",
            "type": "Array<Forwarded>"
        }    ];

    static getAttributeTypeMap() {
        return ForwardStoredMessageResponse.attributeTypeMap;
    }
}

