/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class GetAuditResponse {
    /**
    * Indicates successful response
    */
    'success': boolean;
    /**
    * Users unique ID.
    */
    'user': string;
    /**
    * Start time as ISO date
    */
    'start'?: Date;
    /**
    * End time as ISO date
    */
    'end'?: Date;
    /**
    * Expiration date. Audit data is deleted after this date
    */
    'expires': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "Date"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date"
        },
        {
            "name": "expires",
            "baseName": "expires",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GetAuditResponse.attributeTypeMap;
    }
}

