/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class GetAutoreplyResponse {
    /**
    * Indicates successful response
    */
    'success': boolean;
    /**
    * Is the autoreply enabled (true) or not (false)
    */
    'status': boolean;
    /**
    * Name that is used for the From: header in autoreply message
    */
    'name': string;
    /**
    * Subject line for the autoreply. If empty then uses subject of the original message
    */
    'subject': string;
    /**
    * HTML formatted content of the autoreply message
    */
    'html': string;
    /**
    * Plaintext formatted content of the autoreply message
    */
    'text': string;
    /**
    * Datestring of the start of the autoreply
    */
    'start': Date;
    /**
    * Datestring of the end of the autoreply
    */
    'end': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "html",
            "baseName": "html",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "Date"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GetAutoreplyResponse.attributeTypeMap;
    }
}

