/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class GetAddressesResult {
    /**
    * ID of the Address
    */
    'id': string;
    /**
    * Identity name
    */
    'name': string;
    /**
    * E-mail address string
    */
    'address': string;
    /**
    * User ID this address belongs to if this is a User address
    */
    'user': string;
    /**
    * If true then it is a forwarded address
    */
    'forwarded': boolean;
    /**
    * If true then the forwarded address is disabled
    */
    'forwardedDisabled': boolean;
    /**
    * List of forwarding targets
    */
    'target'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "forwarded",
            "baseName": "forwarded",
            "type": "boolean"
        },
        {
            "name": "forwardedDisabled",
            "baseName": "forwardedDisabled",
            "type": "boolean"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return GetAddressesResult.attributeTypeMap;
    }
}

