/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { DnsTxt } from './dnsTxt';

export class GetDkimKeyResponse {
    /**
    * Indicates successful response
    */
    'success': boolean;
    /**
    * ID of the DKIM
    */
    'id': string;
    /**
    * The domain this DKIM key applies to
    */
    'domain': string;
    /**
    * DKIM selector
    */
    'selector': string;
    /**
    * Key description
    */
    'description': string;
    /**
    * Key fingerprint (SHA1)
    */
    'fingerprint': string;
    /**
    * Public key in DNS format (no prefix/suffix, single line)
    */
    'publicKey': string;
    'dnsTxt': DnsTxt;
    /**
    * Datestring
    */
    'created': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "selector",
            "baseName": "selector",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "publicKey",
            "baseName": "publicKey",
            "type": "string"
        },
        {
            "name": "dnsTxt",
            "baseName": "dnsTxt",
            "type": "DnsTxt"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GetDkimKeyResponse.attributeTypeMap;
    }
}

