/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class GetDkimKeysResult {
    /**
    * ID of the DKIM
    */
    'id': string;
    /**
    * The domain this DKIM key applies to
    */
    'domain': string;
    /**
    * DKIM selector
    */
    'selector': string;
    /**
    * Key description
    */
    'description': string;
    /**
    * Key fingerprint (SHA1)
    */
    'fingerprint': string;
    /**
    * Datestring
    */
    'created': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "selector",
            "baseName": "selector",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GetDkimKeysResult.attributeTypeMap;
    }
}

