/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class GetUserAddressesResult {
    /**
    * ID of the Address
    */
    'id': string;
    /**
    * Identity name
    */
    'name': string;
    /**
    * E-mail address string
    */
    'address': string;
    /**
    * Indicates if this is the default address for the User
    */
    'main': boolean;
    /**
    * Datestring of the time the address was created
    */
    'created': Date;
    /**
    * List of tags associated with the Address
    */
    'tags': Array<string>;
    /**
    * Metadata object (if available)
    */
    'metaData'?: object;
    /**
    * Internal metadata object (if available), not included for user-role requests
    */
    'internalData'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "main",
            "baseName": "main",
            "type": "boolean"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "object"
        },
        {
            "name": "internalData",
            "baseName": "internalData",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return GetUserAddressesResult.attributeTypeMap;
    }
}

