/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Information about public key or false if key is not available
*/
export class KeyInfo {
    /**
    * Name listed in public key
    */
    'name': string;
    /**
    * E-mail address listed in public key
    */
    'address': string;
    /**
    * Fingerprint of the public key
    */
    'fingerprint': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return KeyInfo.attributeTypeMap;
    }
}

