/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Optional names for special mailboxes
*/
export class Mailboxes {
    /**
    * Path of Sent Mail folder
    */
    'sent'?: string;
    /**
    * Path of spam folder
    */
    'junk'?: string;
    /**
    * Path of drafts folder
    */
    'drafts'?: string;
    /**
    * Path of trash folder
    */
    'trash'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sent",
            "baseName": "sent",
            "type": "string"
        },
        {
            "name": "junk",
            "baseName": "junk",
            "type": "string"
        },
        {
            "name": "drafts",
            "baseName": "drafts",
            "type": "string"
        },
        {
            "name": "trash",
            "baseName": "trash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Mailboxes.attributeTypeMap;
    }
}

