/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Message information
*/
export class Message {
    /**
    * Message ID in mailbox
    */
    'id': number;
    /**
    * Mailbox ID the message was stored into
    */
    'mailbox': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "mailbox",
            "baseName": "mailbox",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Message.attributeTypeMap;
    }
}

