/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* POP3 download quota
*/
export class Pop3Download {
    /**
    * How many bytes per 24 hours can be downloaded via POP3. Only message contents are counted, not protocol overhead.
    */
    'allowed': number;
    /**
    * How many bytes are downloaded during current 24 hour period
    */
    'used': number;
    /**
    * Time until the end of current 24 hour period
    */
    'ttl': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowed",
            "baseName": "allowed",
            "type": "number"
        },
        {
            "name": "used",
            "baseName": "used",
            "type": "number"
        },
        {
            "name": "ttl",
            "baseName": "ttl",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Pop3Download.attributeTypeMap;
    }
}

