/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Quota usage limits
*/
export class Quota {
    /**
    * Allowed quota of the user in bytes
    */
    'allowed': number;
    /**
    * Space used in bytes
    */
    'used': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowed",
            "baseName": "allowed",
            "type": "number"
        },
        {
            "name": "used",
            "baseName": "used",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Quota.attributeTypeMap;
    }
}

