/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Array of addresses from RCPT TO (should have just one normally)
*/
export class Rcpt {
    /**
    * RCPT TO address as provided by SMTP client
    */
    'value': string;
    /**
    * Normalized RCPT address
    */
    'formatted': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "formatted",
            "baseName": "formatted",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Rcpt.attributeTypeMap;
    }
}

