/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Optional referenced email. If submitted message is a reply and relevant fields are not provided then these are resolved from the message to be replied to
*/
export class Reference {
    /**
    * Mailbox ID
    */
    'mailbox': string;
    /**
    * Message ID in Mailbox
    */
    'id': number;
    /**
    * Either reply, replyAll or forward
    */
    'action': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mailbox",
            "baseName": "mailbox",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Reference.attributeTypeMap;
    }
}

