/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class RestoreMessageRequest {
    /**
    * ID of the target Mailbox. If not set then original mailbox is used.
    */
    'mailbox'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mailbox",
            "baseName": "mailbox",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RestoreMessageRequest.attributeTypeMap;
    }
}

