/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class SetupTotp2FAResponse {
    /**
    * Indicates successful response
    */
    'success': boolean;
    /**
    * Generated TOTP seed value
    */
    'seed': string;
    /**
    * Base64 encoded QR code
    */
    'qrcode': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "seed",
            "baseName": "seed",
            "type": "string"
        },
        {
            "name": "qrcode",
            "baseName": "qrcode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SetupTotp2FAResponse.attributeTypeMap;
    }
}

