/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Either special use identifier or null. One of \\Drafts, \\Junk, \\Sent or \\Trash
*/
export enum SpecialUse {
    Drafts = <any> '\\Drafts',
    Junk = <any> '\\Junk',
    Sent = <any> '\\Sent',
    Trash = <any> '\\Trash'
}
