/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* TLS information. Value is false if TLS was not used
*/
export class Tls {
    /**
    * Cipher name, eg \"ECDHE-RSA-AES128-GCM-SHA256\"
    */
    'name': object;
    /**
    * TLS version, eg \"TLSv1/SSLv3\"
    */
    'version': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "object"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return Tls.attributeTypeMap;
    }
}

