/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class UpdateMessageResponse {
    /**
    * Indicates successful response
    */
    'success': boolean;
    /**
    * If messages were moved then lists new ID values. Array entry is an array with first element pointing to old ID and second to new ID
    */
    'id': Array<object>;
    /**
    * If messages were not moved, then indicates the number of updated messages
    */
    'updated': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "Array<object>"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateMessageResponse.attributeTypeMap;
    }
}

