/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class UpdateMailboxRequest {
    /**
    * Full path of the mailbox, use this to rename an existing Mailbox
    */
    'path'?: string;
    /**
    * Is the folder hidden or not. Hidden folders can not be opened in IMAP.
    */
    'hidden'?: boolean;
    /**
    * Retention policy for the Mailbox. Changing retention value only affects messages added to this folder after the change
    */
    'retention'?: number;
    /**
    * Change Mailbox subscription state
    */
    'subscribed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean"
        },
        {
            "name": "retention",
            "baseName": "retention",
            "type": "number"
        },
        {
            "name": "subscribed",
            "baseName": "subscribed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateMailboxRequest.attributeTypeMap;
    }
}

