/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Autoreply } from './autoreply';

export class UpdateForwardedAddressRequest {
    /**
    * New address. Only affects normal addresses, special addresses that include * can not be changed
    */
    'address'?: string;
    /**
    * Identity name
    */
    'name'?: string;
    /**
    * An array of forwarding targets. The value could either be an email address or a relay url to next MX server (\"smtp://mx2.zone.eu:25\") or an URL where mail contents are POSTed to. If set then overwrites previous targets array
    */
    'targets'?: Array<string>;
    /**
    * Daily allowed forwarding count for this address
    */
    'forwards'?: number;
    /**
    * A list of tags associated with this address
    */
    'tags'?: Array<string>;
    /**
    * Optional metadata, must be an object or JSON formatted string
    */
    'metaData'?: object | string;
    /**
    * Optional metadata for internal use, must be an object or JSON formatted string of an object. Not available for user-role tokens
    */
    'internalData'?: object | string;
    /**
    * If true then disables forwarded address (stops forwarding messages)
    */
    'forwardedDisabled'?: boolean;
    'autoreply'?: Autoreply;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "targets",
            "baseName": "targets",
            "type": "Array<string>"
        },
        {
            "name": "forwards",
            "baseName": "forwards",
            "type": "number"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "object | string"
        },
        {
            "name": "internalData",
            "baseName": "internalData",
            "type": "object | string"
        },
        {
            "name": "forwardedDisabled",
            "baseName": "forwardedDisabled",
            "type": "boolean"
        },
        {
            "name": "autoreply",
            "baseName": "autoreply",
            "type": "Autoreply"
        }    ];

    static getAttributeTypeMap() {
        return UpdateForwardedAddressRequest.attributeTypeMap;
    }
}

