/**
 * WildDuck API
 * WildDuck API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Forwards } from './forwards';
import { ImapDownload } from './imapDownload';
import { ImapMaxConnections } from './imapMaxConnections';
import { ImapUpload } from './imapUpload';
import { Pop3Download } from './pop3Download';
import { Quota } from './quota';
import { Received } from './received';
import { Recipients } from './recipients';

/**
* Account limits and usage
*/
export class UserLimits {
    'quota': Quota;
    'recipients': Recipients;
    'forwards': Forwards;
    'received': Received;
    'imapUpload': ImapUpload;
    'imapDownload': ImapDownload;
    'pop3Download': Pop3Download;
    'imapMaxConnections'?: ImapMaxConnections;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "quota",
            "baseName": "quota",
            "type": "Quota"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Recipients"
        },
        {
            "name": "forwards",
            "baseName": "forwards",
            "type": "Forwards"
        },
        {
            "name": "received",
            "baseName": "received",
            "type": "Received"
        },
        {
            "name": "imapUpload",
            "baseName": "imapUpload",
            "type": "ImapUpload"
        },
        {
            "name": "imapDownload",
            "baseName": "imapDownload",
            "type": "ImapDownload"
        },
        {
            "name": "pop3Download",
            "baseName": "pop3Download",
            "type": "Pop3Download"
        },
        {
            "name": "imapMaxConnections",
            "baseName": "imapMaxConnections",
            "type": "ImapMaxConnections"
        }    ];

    static getAttributeTypeMap() {
        return UserLimits.attributeTypeMap;
    }
}

